# Generated by Django 5.1.4 on 2024-12-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=40, verbose_name='Название')),
                ('model_name', models.TextField(max_length=40, verbose_name='Наименование модели')),
                ('year', models.TextField(max_length=4, verbose_name='Год выпуска')),
                ('country', models.TextField(max_length=20, verbose_name='Страна производитель')),
            ],
        ),
    ]
